#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2025.1 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : AMD Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Tue Jun 24 13:57:25 AEST 2025
# SW Build 6140274 on Wed May 21 22:58:25 MDT 2025
#
# Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
# Copyright 2022-2025 Advanced Micro Devices, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim tb_top_func_impl -key {Post-Implementation:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view /home/grey/Documents/2025/software projects/DigilentArty_PMOD-OLED-bitmap/tb_top_behav.wcfg -log simulate.log"
xsim tb_top_func_impl -key {Post-Implementation:sim_1:Functional:tb_top} -tclbatch tb_top.tcl -view /home/grey/Documents/2025/software projects/DigilentArty_PMOD-OLED-bitmap/tb_top_behav.wcfg -log simulate.log

