# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: /home/grey/Documents/2025/software projects/digilent-xdc-master/Arty-A7-35-Master.xdc

# IP: ip/mem_oled_char_lib/mem_oled_char_lib.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==mem_oled_char_lib || ORIG_REF_NAME==mem_oled_char_lib} -quiet] -quiet

# IP: ip/clk_wiz_0/clk_wiz_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] -quiet

# XDC: /home/grey/Documents/2025/software projects/DigilentArty_PMOD-OLED-bitmap/DigilentArty_PMOD-OLED-bitmap.gen/sources_1/ip/mem_oled_char_lib/mem_oled_char_lib_ooc.xdc

# XDC: /home/grey/Documents/2025/software projects/DigilentArty_PMOD-OLED-bitmap/DigilentArty_PMOD-OLED-bitmap.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc
set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grey/Documents/2025/software projects/DigilentArty_PMOD-OLED-bitmap/DigilentArty_PMOD-OLED-bitmap.gen/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc
#dup# set_property KEEP_HIERARCHY SOFT [get_cells [split [join [get_cells -hier -filter {REF_NAME==clk_wiz_0 || ORIG_REF_NAME==clk_wiz_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: /home/grey/Documents/2025/software projects/DigilentArty_PMOD-OLED-bitmap/DigilentArty_PMOD-OLED-bitmap.gen/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc
